"""usbs_data_null_true

Revision ID: 0e0e91aba46f
Revises: bd3feb6c3626
Create Date: 2025-05-16 11:05:27.290801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e0e91aba46f'
down_revision: Union[str, None] = 'bd3feb6c3626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usbs', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usbs', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
