version: '3.8'
services:
  db:
    image: postgres:latest
    restart: no
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
#    environment:
#      POSTGRES_DB: usb_mon_db
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: no
    volumes:
      - ./redisdata:/data
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"

volumes:
  postgres-data:
 